import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
export const dynamic = 'force-dynamic';

export default async function IntegrationDocs({searchParams}: {searchParams: Promise<{site?: string}>}) {
 await requireUser();
 const {site: key} = await searchParams;
 const site = key ? await db.site.findUnique({where: {key}}) : null;
 if (!site) notFound();
 const appUrl = (process.env.APP_URL || '').replace(/\/$/, '');
 const eventNames = [...new Set([...site.funnelSteps, site.conversionEvent])].filter(name => name !== 'page_view');
 return <main className="mx-auto w-full max-w-[1180px] p-5 md:p-8">
  <Link className="text-[#1664d8] underline underline-offset-4 hover:text-[#1664d8]/80" href={`/dashboard?site=${site.key}`}>← Wróć do dashboardu</Link>
  <div className="flex flex-col items-start justify-between gap-4 py-8 md:flex-row md:items-center"><div><small className="text-xs leading-relaxed text-slate-500">DOKUMENTACJA INTEGRACJI</small><h1 className="my-3 text-3xl font-bold tracking-tight text-slate-900 md:text-[38px]">{site.name}</h1><p className="my-3 leading-relaxed text-slate-500">Co dodać na stronie, żeby mierzyć ruch i wybrane zdarzenia.</p></div></div>
  <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-4 text-lg font-semibold text-slate-900">1. Skonfiguruj adresy strony</h2><p className="my-3 leading-relaxed text-slate-500">Dozwolone originy: <strong>{site.origins.join(', ')}</strong>. Origin to protokół, domena i opcjonalny port, bez ścieżki i końcowego ukośnika. Dodaj osobno adres z www, bez www oraz lokalny adres, jeśli chcesz testować lokalnie.</p><p className="my-3 leading-relaxed text-slate-500">Zdarzenie konwersji: <code className="font-mono text-[0.9em] text-[#1664d8]">{site.conversionEvent}</code>. Kroki: {site.funnelSteps.join(' → ') || 'Brak skonfigurowanych kroków'}.</p></section>
  <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-4 text-lg font-semibold text-slate-900">2. Dodaj tracker</h2><p className="my-3 leading-relaxed text-slate-500">Umieść ten kod w każdej stronie przed <code className="font-mono text-[0.9em] text-[#1664d8]">&lt;/head&gt;</code> albo we wspólnym layoucie aplikacji. Załaduj tracker jeden raz.</p><pre className="my-4 overflow-auto rounded-lg border border-slate-200 bg-slate-50 p-4 font-mono text-[13px] leading-relaxed text-slate-700">{`<script defer src="${appUrl}/tracker.js" data-site="${site.key}"></script>`}</pre><p className="my-3 leading-relaxed text-slate-500">Odsłony (<code className="font-mono text-[0.9em] text-[#1664d8]">page_view</code>) są wysyłane automatycznie, również przy zmianach ścieżki przez pushState, replaceState i popstate. Nie dodawaj własnego zdarzenia odsłony.</p></section>
  <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-4 text-lg font-semibold text-slate-900">3. Oznacz kliknięcia i własne zdarzenia</h2><p className="my-3 leading-relaxed text-slate-500">Przykład kliknięcia: dodaj atrybuty do istniejącego przycisku lub linku. Nazwę zdarzenia dobierz do swoich kroków.</p><pre className="my-4 overflow-auto rounded-lg border border-slate-200 bg-slate-50 p-4 font-mono text-[13px] leading-relaxed text-slate-700">{`<a href="/contact" data-analytics="button_clicked" data-analytics-location="hero">Kontakt</a>`}</pre><p className="my-3 leading-relaxed text-slate-500">Dla innych akcji wywołaj funkcję track w odpowiednim miejscu swojego kodu. Konwersję wysyłaj dopiero po potwierdzeniu sukcesu danej akcji, np. przez backend. Nie oznaczaj tego samego zdarzenia jednocześnie atrybutem i wywołaniem track.</p><pre className="my-4 overflow-auto rounded-lg border border-slate-200 bg-slate-50 p-4 font-mono text-[13px] leading-relaxed text-slate-700">{`// Po potwierdzeniu sukcesu akcji:\nwindow.analytics?.track(${JSON.stringify(site.conversionEvent)}, { form: 'contact' });`}</pre>{eventNames.length > 0 && <details className="my-4 rounded-xl border border-slate-200 bg-slate-50 p-5"><summary className="cursor-pointer text-sm font-medium text-[#1664d8]">Wywołania dla zdarzeń tej strony</summary><pre className="my-4 overflow-auto rounded-lg border border-slate-200 bg-slate-50 p-4 font-mono text-[13px] leading-relaxed text-slate-700">{eventNames.map(name => `window.analytics?.track(${JSON.stringify(name)});`).join('\n')}</pre><p className="my-3 leading-relaxed text-slate-500">Każde wywołanie umieść przy odpowiadającej mu akcji; nie uruchamiaj całej listy naraz. Tracker musi być już załadowany.</p></details>}<p className="my-3 leading-relaxed text-slate-500">Konfiguracja kroków i konwersji określa sposób prezentacji danych. Sama nie uruchamia zdarzeń na stronie. Pulse przyjmuje również inne poprawne nazwy zdarzeń.</p></section>
  <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-4 text-lg font-semibold text-slate-900">4. Sprawdź integrację</h2><ol className="my-3 list-decimal space-y-2 pl-5 leading-relaxed text-slate-600"><li>Otwórz stronę z dozwolonego adresu i przejdź między podstronami.</li><li>Wykonaj oznaczone kliknięcie i akcję konwersji.</li><li>Odśwież dashboard i sprawdź odsłony oraz listę zdarzeń.</li><li>Jeśli nie ma danych, sprawdź w narzędziach przeglądarki, czy tracker.js się załadował i POST do /api/event otrzymuje odpowiedź 204. Zweryfikuj klucz strony, origin oraz ustawienia prywatności i zgody.</li></ol></section>
  <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-4 text-lg font-semibold text-slate-900">Ustawienia strony i prywatność</h2><p className="my-3 leading-relaxed text-slate-500">Jeśli używasz CSP, dopuść <code className="font-mono text-[0.9em] text-[#1664d8]">{appUrl}</code> w script-src i connect-src. Tracker korzysta z localStorage; gdy strona wymaga zgody, załaduj go dopiero po jej uzyskaniu. Przy aktywnym Do Not Track lub Global Privacy Control dane nie są zbierane.</p><p className="my-3 leading-relaxed text-slate-500">Nie wysyłaj danych osobowych ani sekretów w nazwach, ścieżkach, UTM-ach lub właściwościach. Właściwości mogą zawierać do 10 prostych wartości (tekst do 200 znaków, liczba lub boolean). Nazwy zdarzeń: do 64 znaków, małe litery, cyfry i podkreślenia, zaczynając od litery.</p><p className="my-3 leading-relaxed text-slate-500">Kroki pokazują unikalnych odwiedzających dla każdego zdarzenia w okresie; nie sprawdzają kolejności. Konwersja to udział odwiedzających, którzy wysłali skonfigurowane zdarzenie konwersji.</p></section>
 </main>;
}
