[program:pulse]
directory=/var/www/pulse
command=/usr/bin/node /var/www/pulse/node_modules/next/dist/bin/next start -H 127.0.0.1 -p 3000
user=ubuntu
environment=NODE_ENV="production"
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/pulse.log
stderr_logfile=/var/log/supervisor/pulse-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
